# Generated by Django 3.2.4 on 2021-06-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagement',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
