# Generated by Django 3.2.4 on 2021-06-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0004_auto_20210611_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagement',
            name='image',
            field=models.ImageField(upload_to='assets/'),
        ),
    ]
