# Generated by Django 3.2.4 on 2021-06-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0005_alter_projectmanagement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectmanagement',
            name='image',
            field=models.ImageField(null=True, upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='projectmanagement',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='taskmanagement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmanagement',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
