# Generated by Django 3.2.4 on 2021-06-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0006_auto_20210612_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagement',
            name='duration',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
